"""Op declaration and signature introspection, from opspec.

skop's spec layer is opspec's: everything here is ``opspec.op``, re-exported
under the module path skop's own code and older callers import from. Where
the two used to differ, and which way each difference went, is in
opspec/docs/design/0003-reconciling-with-scikit-ops.md.
"""

from __future__ import annotations

from opspec.op import (
    ALIASES,
    BOOL,
    CANONICAL,
    COMPUTER,
    ENUM,
    FLOAT,
    FUNCTION,
    INPLACE,
    INT,
    MUT,
    NDARRAY,
    OUT,
    PATH,
    STR,
    UNKNOWN,
    WILDCARD,
    WIRE_TYPES,
    Axes,
    Choice,
    Choices,
    Mut,
    OpSpec,
    Out,
    OutputSpec,
    ParamsFor,
    ParamSpec,
    Role,
    Slot,
    TypeSpec,
    _strip,
    axes_of,
    canonical,
    choices_of,
    direction_of,
    is_op,
    op,
    params_for_of,
    role_of,
    type_spec,
)

__all__ = [
    "ALIASES",
    "BOOL",
    "CANONICAL",
    "COMPUTER",
    "ENUM",
    "FLOAT",
    "FUNCTION",
    "INPLACE",
    "INT",
    "MUT",
    "NDARRAY",
    "OUT",
    "PATH",
    "STR",
    "UNKNOWN",
    "WILDCARD",
    "WIRE_TYPES",
    "Axes",
    "Choice",
    "Choices",
    "Mut",
    "OpSpec",
    "Out",
    "OutputSpec",
    "ParamSpec",
    "ParamsFor",
    "Role",
    "Slot",
    "TypeSpec",
    "_strip",
    "axes_of",
    "canonical",
    "choices_of",
    "direction_of",
    "is_op",
    "op",
    "params_for_of",
    "role_of",
    "type_spec",
]
